# Generated by Django 5.1 on 2025-03-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_loan_customer_alter_payment_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='loan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.loan'),
        ),
    ]
