# Generated by Django 5.1 on 2025-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_payment_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprovider',
            name='fund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Funds available for loan taking.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanprovider',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Earnings from paid back loans.', max_digits=12),
        ),
    ]
