# Generated by Django 5.1 on 2025-03-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_loanprovider_fund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending_repayment', 'Pending Repayment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted')], default='pending_repayment', max_length=20),
        ),
    ]
