# Generated by Django 5.1 on 2025-03-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
            preserve_default=False,
        ),
    ]
